apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.31.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: database
  name: database
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: database
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.31.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/kubernetes-directus: "true"
        io.kompose.service: database
    spec:
      containers:
        - env:
            - name: POSTGRES_DATABASE
              valueFrom:
                configMapKeyRef:
                  key: DB_DATABASE
                  name: config-map
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: DB_PASSWORD
                  name: config-map
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  key: DB_USER
                  name: config-map
          image: postgis/postgis:16-3.4
          name: database
          ports:
            - containerPort: 5432
              hostPort: 5432
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: db
      restartPolicy: Always
      volumes:
        - name: db
          persistentVolumeClaim:
            claimName: db
status: {}
