apiVersion: v1
kind: PersistentVolume
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: db
  name: db
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteMany
  storageClassName: manual
  hostPath:
    path: /Users/tdespenza/Projects/tdespenza/quantum-software/quantum-bank-cms/database
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: db
  name: db
  namespace: default
spec:
  volumeName: db
  accessModes:
    - ReadWriteMany
  storageClassName: manual
  resources:
    requests:
      storage: 8Gi
status: {}
