version: "3.8"

services:
  database:
    restart: unless-stopped
    env_file: .env
    image: bitnami/postgresql:15.4.0
    platform: linux/amd64
    environment:
      POSTGRESQL_USER: ${DB_USER}
      POSTGRESQL_PASSWORD: ${DB_PASSWORD}
      POSTGRESQL_DATABASE: ${DB_DATABASE}
    volumes:
      - db:/bitnami/postgresql
    ports:
      - '5432:5432'
    networks:
      - directus

  cache:
    image: redis:6
    ports:
      - '6379:6379'
    networks:
      - directus

  directus:
    restart: unless-stopped
    env_file: .env
    image: directus/directus:10.6.1
    platform: linux/amd64
    ports:
      - 8055:8055
    volumes:
      - ./database:/directus/database
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
    depends_on:
      - cache
      - database
    environment:
      KEY: ${KEY}
      SECRET: ${SECRET}
      DB_CLIENT: ${DB_CLIENT}
      DB_HOST: database
      DB_PORT: ${DB_HOST}
      DB_DATABASE: ${DB_DATABASE}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      CACHE_ENABLED: ${CACHE_ENABLED}
      CACHE_STORE: ${CACHE_STORE}
      REDIS: redis://cache:6379
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      PUBLIC_URL: ${PUBLIC_URL}
    networks:
      - directus

networks:
  directus:
    driver: bridge

volumes:
  db:
