version: "3.8"

services:
  database:
    restart: always
    env_file: .env
    image: bitnami/postgresql:15.4.0
    platform: linux/amd64
    environment:
      POSTGRESQL_USER: ${DB_USER}
      POSTGRESQL_PASSWORD: ${DB_PASSWORD}
      POSTGRESQL_DATABASE: ${DB_DATABASE}
    volumes:
      - db:/bitnami/postgresql
    ports:
      - '5432:5432'
    networks:
      - directus

  cache:
    image: redis:6
    ports:
      - '6379:6379'
    networks:
      - directus

  directus:
    restart: always
    env_file: .env
    image: directus/directus:10.6.4
    platform: linux/amd64
    ports:
      - 8055:8055
    volumes:
      - ./database:/directus/database
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
    depends_on:
      - cache
      - database
    environment:
      REDIS: redis://cache:6379
    networks:
      - directus

networks:
  directus:
    driver: bridge

volumes:
  db:
