apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: directus-claim2
  name: directus-claim2
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: do-block-storage-retain
  resources:
    requests:
      storage: 100Mi
status: {}
