apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.31.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: directus
  name: directus
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: directus
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.31.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/kubernetes-directus: "true"
        io.kompose.service: directus
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - env:
          - name: ACCESS_TOKEN_TTL
            valueFrom:
              configMapKeyRef:
                key: ACCESS_TOKEN_TTL
                name: config-map
          - name: ADMIN_EMAIL
            valueFrom:
              secretKeyRef:
                key: ADMIN_EMAIL
                name: admin
          - name: ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                key: ADMIN_PASSWORD
                name: admin
          - name: ASSETS_CACHE_TTL
            valueFrom:
              configMapKeyRef:
                key: ASSETS_CACHE_TTL
                name: config-map
          - name: CACHE_ENABLED
            valueFrom:
              configMapKeyRef:
                key: CACHE_ENABLED
                name: config-map
          - name: CACHE_STORE
            valueFrom:
              configMapKeyRef:
                key: CACHE_STORE
                name: config-map
          - name: CORS_ALLOWED_HEADERS
            valueFrom:
              configMapKeyRef:
                key: CORS_ALLOWED_HEADERS
                name: config-map
          - name: CORS_CREDENTIALS
            valueFrom:
              configMapKeyRef:
                key: CORS_CREDENTIALS
                name: config-map
          - name: CORS_ENABLED
            valueFrom:
              configMapKeyRef:
                key: CORS_ENABLED
                name: config-map
          - name: CORS_EXPOSED_HEADERS
            valueFrom:
              configMapKeyRef:
                key: CORS_EXPOSED_HEADERS
                name: config-map
          - name: CORS_MAX_AGE
            valueFrom:
              configMapKeyRef:
                key: CORS_MAX_AGE
                name: config-map
          - name: CORS_METHODS
            valueFrom:
              configMapKeyRef:
                key: CORS_METHODS
                name: config-map
          - name: CORS_ORIGIN
            valueFrom:
              configMapKeyRef:
                key: CORS_ORIGIN
                name: config-map
          - name: DB_CLIENT
            valueFrom:
              configMapKeyRef:
                key: DB_CLIENT
                name: config-map
          - name: DB_DATABASE
            valueFrom:
              secretKeyRef:
                key: DB_DATABASE
                name: db
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                key: DB_HOST
                name: config-map
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                key: DB_PASSWORD
                name: db
          - name: DB_PORT
            valueFrom:
              configMapKeyRef:
                key: DB_PORT
                name: config-map
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                key: DB_USER
                name: db
          - name: EMAIL_FROM
            valueFrom:
              configMapKeyRef:
                key: EMAIL_FROM
                name: config-map
          - name: EMAIL_TRANSPORT
            valueFrom:
              configMapKeyRef:
                key: EMAIL_TRANSPORT
                name: config-map
          - name: EMAIL_SMTP_HOST
            valueFrom:
              configMapKeyRef:
                key: EMAIL_SMTP_HOST
                name: config-map
          - name: EMAIL_SMTP_NAME
            valueFrom:
              configMapKeyRef:
                key: EMAIL_SMTP_NAME
                name: config-map
          - name: EMAIL_SMTP_POOL
            valueFrom:
              configMapKeyRef:
                key: EMAIL_SMTP_POOL
                name: config-map
          - name: EMAIL_SMTP_PORT
            valueFrom:
              configMapKeyRef:
                key: EMAIL_SMTP_PORT
                name: config-map
          - name: EMAIL_SMTP_SECURE
            valueFrom:
              configMapKeyRef:
                key: EMAIL_SMTP_SECURE
                name: config-map
          - name: EMAIL_SMTP_IGNORE_TLS
            valueFrom:
              configMapKeyRef:
                key: EMAIL_SMTP_IGNORE_TLS
                name: config-map
          - name: EMAIL_SMTP_USER
            valueFrom:
              configMapKeyRef:
                key: EMAIL_SMTP_USER
                name: config-map
          - name: EMAIL_SMTP_PASSWORD
            valueFrom:
              secretKeyRef:
                key: EMAIL_SMTP_PASSWORD
                name: smtp
          - name: EXTENSIONS_AUTO_RELOAD
            valueFrom:
              configMapKeyRef:
                key: EXTENSIONS_AUTO_RELOAD
                name: config-map
          - name: EXTENSIONS_PATH
            valueFrom:
              configMapKeyRef:
                key: EXTENSIONS_PATH
                name: config-map
          - name: HOST
            valueFrom:
              configMapKeyRef:
                key: HOST
                name: config-map
          - name: KEY
            valueFrom:
              secretKeyRef:
                key: KEY
                name: security
          - name: PORT
            valueFrom:
              configMapKeyRef:
                key: PORT
                name: config-map
          - name: PUBLIC_URL
            valueFrom:
              configMapKeyRef:
                key: PUBLIC_URL
                name: config-map
          - name: RATE_LIMITER_DURATION
            valueFrom:
              configMapKeyRef:
                key: RATE_LIMITER_DURATION
                name: config-map
          - name: RATE_LIMITER_ENABLED
            valueFrom:
              configMapKeyRef:
                key: RATE_LIMITER_ENABLED
                name: config-map
          - name: RATE_LIMITER_POINTS
            valueFrom:
              configMapKeyRef:
                key: RATE_LIMITER_POINTS
                name: config-map
          - name: RATE_LIMITER_STORE
            valueFrom:
              configMapKeyRef:
                key: RATE_LIMITER_STORE
                name: config-map
          - name: REDIS
            valueFrom:
              configMapKeyRef:
                key: REDIS
                name: config-map
          - name: REFRESH_TOKEN_COOKIE_NAME
            valueFrom:
              configMapKeyRef:
                key: REFRESH_TOKEN_COOKIE_NAME
                name: config-map
          - name: REFRESH_TOKEN_COOKIE_SAME_SITE
            valueFrom:
              configMapKeyRef:
                key: REFRESH_TOKEN_COOKIE_SAME_SITE
                name: config-map
          - name: REFRESH_TOKEN_COOKIE_SECURE
            valueFrom:
              configMapKeyRef:
                key: REFRESH_TOKEN_COOKIE_SECURE
                name: config-map
          - name: REFRESH_TOKEN_TTL
            valueFrom:
              configMapKeyRef:
                key: REFRESH_TOKEN_TTL
                name: config-map
          - name: SECRET
            valueFrom:
              secretKeyRef:
                key: SECRET
                name: security
          - name: STORAGE_LOCAL_DRIVER
            valueFrom:
              configMapKeyRef:
                key: STORAGE_LOCAL_DRIVER
                name: config-map
          - name: STORAGE_LOCAL_ROOT
            valueFrom:
              configMapKeyRef:
                key: STORAGE_LOCAL_ROOT
                name: config-map
          - name: STORAGE_LOCATIONS
            valueFrom:
              configMapKeyRef:
                key: STORAGE_LOCATIONS
                name: config-map
          image: directus/directus:10.8.2
          name: directus
          ports:
            - containerPort: 8055
              hostPort: 8055
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /directus/database
              name: directus-claim0
            - mountPath: /directus/uploads
              name: directus-claim1
            - mountPath: /directus/extensions
              name: directus-claim2
        - name: zerotier-sidecar
          image: zerotier/zerotier:latest
          args: ["join", "db64858fed1eabd7"]
          securityContext:
            privileged: true
      restartPolicy: Always
      volumes:
        - name: directus-claim0
          persistentVolumeClaim:
            claimName: directus-claim0
        - name: directus-claim1
          persistentVolumeClaim:
            claimName: directus-claim1
        - name: directus-claim2
          persistentVolumeClaim:
            claimName: directus-claim2
status: {}
