apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - directus-volume0.yaml
  - directus-volume1.yaml
  - directus-volume2.yaml
  - directus-service.yaml
  - directus-deployment.yaml
